# Generated by Django 5.0.7 on 2024-08-06 03:09

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="position",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="subjects",
        ),
    ]
